<?php

namespace Container2moIxxT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWordFinderCommand_CommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\WordFinderCommand.command' shared service.
     *
     * @return \Symfony\Component\Console\Command\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/WordFinderCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Find/WordFinder.php';
        include_once \dirname(__DIR__, 4).'/src/Load/WordLoader.php';

        $instance = new \Symfony\Component\Console\Command\Command();

        $instance->setCode((new \App\Command\WordFinderCommand(new \App\Find\WordFinder(new \App\Load\WordLoader())))->__invoke(...));
        $instance->setName('app:find-words');

        return $container->privates['App\\Command\\WordFinderCommand.command'] = $instance;
    }
}
